### ISSUE TITLE
Invoke script outside of openconnect

### ISSUE THREAD

**Issue by danielmihai** [dlenski/vpn-slice#1]
Hi @dlenski ,

How can we run this script after connecting to VPN ? I want to add some domain names to be able to connect via ssh, outside of VPN.

I'm using cisco anyconnect :) 

Thanks,
Daniel.

**Comment by dlenski** [comment]
As far as I know, you can't.

This is a tool for customizing the routing and host naming used by the open source VPN tools, open connect and vpnc.

The official Cisco software does not allow the user any control over the routing configuration. It simply accepts whatever the VPN administrators want you to do. This is one of many reasons not to use closed-source VPN software.

Since Cisco AnyConnect VPNs are perfectly supported by openconnect, why not try using it instead?

**Comment by danielmihai** [comment]
Ok. I have a cisco anyconnect VPN network configured and named as
"office-vpn". How do I invoke the openconnect to connect to that defined
and named VPN network and invoke vpn-slice with 'server1.name.com
server2.name.com server3.name.com'  ?

Thanks a bunch!

**Comment by dlenski** [comment]
As shown on the README here:

```
$ openconnect [the usual parameters] --script 'vpn-slice -v server1.name.com ...'
```

Are you actually using open connect from the command line, or some GUI wrapper around it?

If you're using a GUI, it may or may not have support for invoking a non-default script.

**Comment by danielmihai** [comment]
I'm using the NetworkManager from Ubuntu to connect. I configured a VPN
connection (specify the server etc.) then i click the network icon and
select the VPN, insert username and password and connect.
I haven't used openconnect from terminal before. Do you know how to specify
an already configured VPN network ? this is what i'm asking in fact :)

Thanks!

**Comment by dlenski** [comment]
Ah. Unfortunately, the `network-manager-openconnect-gnome` GUI does not support the ability to invoke a non-default `vpnc-script` currently.

It would be a great addition for power users, though. :+1: 
https://wiki.gnome.org/action/show/Projects/NetworkManager?action=show&redirect=NetworkManager

The examples shown in [the README Usage section](https://github.com/dlenski/vpn-slice#usage) should be enough to get you started with the CLI, but  read the openconnect manual page for more details: http://www.infradead.org/openconnect/manual.html

**Comment by dlenski** [comment]
Any luck?
