### ISSUE TITLE
Dig responds with FORMERR without +nocookie or +noedns

### ISSUE THREAD

**Issue by beanaroo** [dlenski/vpn-slice#10]
Hi @dlenski!

Once again, thank you for making global protect access on Linux a breeze.
I could never get the DNS resolution working with vpn-slice and had some time today to dig (pun intended).
The problem for me is explained in [this post](https://kevinlocke.name/bits/2017/01/20/formerr-from-microsoft-dns-server-for-dig/) and appears to be MS DNS specific.

Once I dropped in either the `+nocookie` or `+noedns` flag, it worked. I'm not too clued up on the implications, however.

**Comment by dlenski** [comment]
Huh… thanks. I haven't run into this problem before (either that or didn't recognize it as such  ¯\\\_(ツ)\_/¯).

I'm wondering if there's any downside to simply including `+noedns` with _all_ the queries issued by `vpn-slice`.

**Comment by dlenski** [comment]
Using `+noedns` everywhere seems to work for me, some I'll stick with that.
