### ISSUE TITLE
Building wheel for setproctitle (pyproject.toml) ... error

### ISSUE THREAD

**Issue by alansenairj** [dlenski/vpn-slice#106]
```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp5bfbqufm
       cwd: /tmp/pip-install-cu2ho2es/setproctitle_85e5579b3630466a80ad4137cc97f104
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  creating build
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSPT_VERSION=1.2.2 -DHAVE_SYS_PRCTL_H=1 -I/usr/include/python3.10 -c src/setproctitle.c -o build/temp.linux-x86_64-3.10/src/setproctitle.o
  In file included from src/spt.h:15,
                   from src/setproctitle.c:14:
  src/spt_python.h:16:10: fatal error: Python.h: Arquivo ou diretório inexistente
     16 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for setproctitle
Failed to build setproctitle
ERROR: Could not build wheels for setproctitle, which is required to install pyproject.toml-based projects
░▒▓  │  ~ ▓▒░ sudo pip3 install https://github.com/dlenski/vpn-slice/archive/master.zip
Collecting https://github.com/dlenski/vpn-slice/archive/master.zip
  Downloading https://github.com/dlenski/vpn-slice/archive/master.zip
     - 36 kB 1.4 MB/s 
  Preparing metadata (setup.py) ... done
Collecting setproctitle
  Using cached setproctitle-1.2.2.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dnspython
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Using legacy 'setup.py install' for vpn-slice, since package 'wheel' is not installed.
Building wheels for collected packages: setproctitle
  Building wheel for setproctitle (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpkqvtcm7v
       cwd: /tmp/pip-install-143yv48s/setproctitle_852ad8bbfbfa4b2d8a7aad44b2a8091b
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  creating build
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSPT_VERSION=1.2.2 -DHAVE_SYS_PRCTL_H=1 -I/usr/include/python3.10 -c src/setproctitle.c -o build/temp.linux-x86_64-3.10/src/setproctitle.o
  In file included from src/spt.h:15,
                   from src/setproctitle.c:14:
  src/spt_python.h:16:10: fatal error: Python.h: Arquivo ou diretório inexistente
     16 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for setproctitle
Failed to build setproctitle
ERROR: Could not build wheels for setproctitle, which is required to install pyproject.toml-based projects
```

**Comment by alansenairj** [comment]
Is it related to python 3.10 version?

**Comment by alansenairj** [comment]
I switched to python 3.9.0 and still getting errors

  │  ~ ▓▒░ sudo pip3 install vpn-slice                                                   ░▒▓ ✔ │ at 18:49:06  ▓▒░
[sudo] senha para alan: 
Collecting vpn-slice
  Using cached vpn_slice-0.16.1-py3-none-any.whl (34 kB)
Collecting setproctitle
  Using cached setproctitle-1.2.2.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dnspython
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Building wheels for collected packages: setproctitle
  Building wheel for setproctitle (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpz93edvem
       cwd: /tmp/pip-install-t3443qt3/setproctitle_4f03e468f2af475599709183379f2dfd
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  creating build
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSPT_VERSION=1.2.2 -DHAVE_SYS_PRCTL_H=1 -I/usr/include/python3.10 -c src/setproctitle.c -o build/temp.linux-x86_64-3.10/src/setproctitle.o
  In file included from src/spt.h:15,
                   from src/setproctitle.c:14:
  src/spt_python.h:16:10: fatal error: Python.h: Arquivo ou diretório inexistente
     16 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for setproctitle
Failed to build setproctitle
ERROR: Could not build wheels for setproctitle, which is required to install pyproject.toml-based projects

**Comment by alansenairj** [comment]
It installed as normal user

░▒▓  │  ~ ▓▒░  pip3 install vpn-slice                                                       ░▒▓ ✔ │ at 18:58:39  ▓▒░
Collecting vpn-slice
  Using cached vpn_slice-0.16.1-py3-none-any.whl (34 kB)
Collecting setproctitle
  Downloading setproctitle-1.2.2-cp39-cp39-manylinux1_x86_64.whl (35 kB)
Collecting dnspython
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Installing collected packages: setproctitle, dnspython, vpn-slice
Successfully installed dnspython-2.1.0 setproctitle-1.2.2 vpn-slice-0.16.1

**Comment by alansenairj** [comment]
the problem was a line in zshrc. 

vi ~/.zshrc and add:
eval "$(pyenv init --path)"


[root@z390]/home/alan# pyenv global 3.9.0
[root@z390]/home/alan# exec $SHELL
[root@z390]/home/alan# python -V
Python 3.9.0
[root@z390]/home/alan# pip3 install vpn-slice
Collecting vpn-slice
  Using cached vpn_slice-0.16.1-py3-none-any.whl (34 kB)
Collecting setproctitle
  Downloading setproctitle-1.2.2-cp39-cp39-manylinux1_x86_64.whl (35 kB)
Collecting dnspython
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Installing collected packages: setproctitle, dnspython, vpn-slice
Successfully installed dnspython-2.1.0 setproctitle-1.2.2 vpn-slice-0.16.1
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/root/.pyenv/versions/3.9.0/bin/python3.9 -m pip install --upgrade pip' command.

**Comment by dlenski** [comment]
What Linux distro are you using? It's not clear that this has anything to do with vpn-slice per se…

What happens if you install [from the `no_required_deps` branch](https://github.com/dlenski/vpn-slice/compare/master...no_required_deps)?

```sh
# omit setproctitle and/or dnspython if those don't work
pip3 install "https://github.com/dlenski/vpn-slice/archive/no_required_deps.zip#egg=vpn-slice[dnspython,setproctitle]"
```

**Comment by alansenairj** [comment]
Hi. I'm using Fedora 35. It has python 3.10 as default and I think it is the problem. i installed python 3.9.0 and select it using pyenv. 

I try to solve it using pyenv to switch root python's default interpreter. 


[root@z390]~/.pyenv/versions/3.9.0/bin# vpn-slice --self-test              
***************************************************************************
*** Self-test passed. Try using vpn-slice with openconnect or vpnc now. ***
***************************************************************************

It worked in switch default python version to root user in some way but I think it cannot working 100%. 

Please check this error below it returns "command not found" when I try to run openconnect with -s option. 



Enviar sondas ESP
Conectado como 172.23.11.198, usando SSL, com ESP em progresso
/bin/sh: linha 1: vpn-slice: comando não encontrado
O script “vpn-slice 192.168.1.0/24 hostname1 alias2=conecta.unimed.com.br=192.168.1.43” retornou erro 127
/bin/sh: linha 1: vpn-slice: comando não encontrado
O script “vpn-slice 192.168.1.0/24 hostname1 alias2=conecta.unimed.com.br=192.168.1.43” retornou erro 127
Sessão ESP estabelecida com o servidor


and got this error too: 

WARNING: Lookup for z390 on VPN DNS servers failed:
        All nameservers failed to answer the query z390. IN A: Server 172.26.4.48 UDP port 53 answered SERVFAIL; Server 172.26.1.21 UDP port 53 answered SERVFAIL

**Comment by alansenairj** [comment]
oh man! you are a genius! thank you very much for this vpn-split tool. You save me! It was very annoying to work with non split vpn. The command --dump you put here https://serverfault.com/questions/331299/how-can-i-stop-openconnect-from-changing-etc-resolv-conf make it work for my case. 

So the problem here was python 3.10. Users must downgrade python version to at least 3.9.0 to make it work in Fedora 35. Users could install pyenv to select correct python version for root. 
I think you can close this and thank you again for this tool!

**Comment by dlenski** [comment]
Perhaps caused by https://github.com/dvarrazzo/py-setproctitle/issues/47#issuecomment-993247979 …?

**Comment by dlenski** [comment]
> Please check this error below it returns "command not found" when I try to run openconnect with -s option.

The README covers this: "You should install as `root` (e.g. using `sudo`), because `openconnect` or `vpnc` will need to be able to invoke `vpn-slice` while running as root:"

If `vpn-slice` isn't in `root`'s path, then you'll need to specify it fully when invoking OpenConnect, e.g.: `openconnect -s "/full/path/to/vpn-slice hostname1 hostname2 1.2.3.0/24"`
