### ISSUE TITLE
Upgrade to Ubuntu 22.04 vpn-slice tun0 "unmanaged"

### ISSUE THREAD

**Issue by PresGas** [dlenski/vpn-slice#110]
On a dist-upgrade to Ubuntu 22.04, I can no longer use `vpn-slice` properly with `openconnect`. NetworkManager shows the tun0 device as "unmanaged":

```
$ nmcli device show
...
GENERAL.DEVICE:                         tun0
GENERAL.TYPE:                           tun
GENERAL.HWADDR:                         (unknown)
GENERAL.MTU:                            1400
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.GATEWAY:                            --
IP6.GATEWAY:                            --
```

I was aware of the resolving issues with linux and am still able to work with that along with `/etc/hosts` is still being written. As a result, I can only get to sites OUTSIDE of the routes in `vpn-slice`. 

```
$ resolvectl
...Link 12 (tun0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 10.79.1.1 10.79.2.2
    DNS Domain: ~domain.com ~another.com 
```
and
```
$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	rusalka

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.79.1.1 dns0.tun0		# vpn-slice-tun0 AUTOCREATED
10.79.2.2 dns1.tun0		# vpn-slice-tun0 AUTOCREATED
```
Let me know if you need other info. Current connection that has worked in the past is:

`sudo openconnect -b --no-dtls --cafile /etc/ssl/certs/ca-certificates.crt --protocol=nc https://vpn.domain.com/groups -u username -s 'vpn-slice 10.79.0.0/16 ...and_about_5_other/16's --verbose --dump';sleep 5;sudo resolvectl dns tun0 10.79.1.1 10.79.2.2;sudo resolvectl domain tun0 "~domain.com" "~another.com"`

**Comment by PresGas** [comment]
Is there anything else you would like for me to gather and provide for this issue?

**Comment by MrGiga** [comment]
I am also having this problem. tun0 shows unmanaged and my /etc/hosts file is not being modified

**Comment by MaciekLeks** [comment]
The same  problem. Anyone solved it somehow?

**Comment by mzient** [comment]
I've checked what happens in openconnect and, to my surprise, I noticed that the script in pre-init stage hangs - I even added some prints in the script in __init__ and main, but they never show up. The call to `waitpid` in openconnect never returns. It was miraculously solved by _not_ specifying `--background` flag for openconnect. Without it, the script is executed correctly. I have no idea why the script (bash? python?) hangs whe run in background in Ubuntu 22.04 but didn't hang on Ubuntu 18.04.

**Comment by jhaemin** [comment]
Same here. It doesn't work with `--background` option.

**Comment by dlenski** [comment]
> Current connection that has worked in the past is:
> 
> `sudo openconnect -b --no-dtls --cafile /etc/ssl/certs/ca-certificates.crt --protocol=nc https://vpn.domain.com/groups -u username -s 'vpn-slice 10.79.0.0/16 ...and_about_5_other/16's --verbose --dump';sleep 5;sudo resolvectl dns tun0 10.79.1.1 10.79.2.2;sudo resolvectl domain tun0 "~domain.com" "~another.com"`

Your `openconnect --script` argument is doing _a lot of work_ here.

In addition to invoking `vpn-slice`, it's also running `resolvectl`. And `resolvectl` knows nothing about the `reason` environment variable, which tells vpn-slice/vpnc-script **what to do** each time that it's invoked.

> I noticed that the script in pre-init stage hangs

This is **not surprising**.

In the pre-init stage, the `tun0` interface _is not up_. So if `resolvectl` tries to send traffic over the interface, it **can't**. It will hang and/or fails. (Must be that something about `resolvectl` changed in Ubuntu 22.04 that causes it to try to send traffic immediately :man_shrugging:)

`vpn-slice` handles this very carefully by putting _itself_ into the background during the connect hook, waiting for the tunnel interface to come up, and then doing "post-connect" actions which require traffic to flow over the VPN interface: https://github.com/dlenski/vpn-slice/blob/master/vpn_slice/__main__.py#L617-L625

If we were to implement a separate post-connect hook in OpenConnect (see [openconnect #117](https://gitlab.com/openconnect/openconnect/-/issues/117)), then this would be a bit easier to implement, but in any case you _cannot_ just put an arbitrary network-using program in the `openconnect --script` argument and expect it to work during the `pre-init` or [pre-]`connect` hooks, where no traffic flows over the VPN interface.

**Comment by dlenski** [comment]
In order to implement [#fancy-split-DNS](https://github.com/dlenski/vpn-slice/labels/fancy-split-DNS) in a way that ordinary users can understand, it should be integrated into `vpn-slice` itself.

I don't use split-DNS myself, so I've been asking for help on implementing this for several years. It appears to be **done** for MacOS, but no one has done it quite right for Linux yet. Help wanted, see: https://github.com/dlenski/vpn-slice/pull/118#issuecomment-1624177196
