### ISSUE TITLE
force all traffic on en0 through utunX on macOS.

### ISSUE THREAD

**Issue by nagydavid** [dlenski/vpn-slice#111]
Hi @dlenski 

I am trying to find a solution  route all traffic on en0(wifi) through utunX tunnel, created by open connect using any connect protocol. It is a corporate VPN, and I need to reach some databases and key vaults. I just recently started using Mac so I have a hard time to figure it out.

I am a noob when it comes to vpn/network/security.

Thank for the help in advance

**Comment by dlenski** [comment]
> I am trying to find a solution **route all traffic** on en0(wifi) **through utunX tunnel**, created by open connect using any connect protocol.

Then vpn-slice probably isn't what you want. The purpose of this tool is to do _the opposite_. I mean, you _could_ use `vpn-slice 0.0.0.0/0` but :man_shrugging:

If you want to route _all_ your traffic through the VPN, then why not just use the default `vpnc-script` which comes with OpenConnect? It simply accepts whatever routes the server sends. If the VPN server wants you to send all your traffic through the VPN, then that's what will happen with OpenConnect + standard `vpnc-script`.

**Comment by nagydavid** [comment]
I have managed to solve it by route2mac libraries and face tunnel to tun interface. But anyway thanks for your good work and answer :)
