### ISSUE TITLE
Don't work on MacOS/arm64

### ISSUE THREAD

**Issue by sj-asm** [dlenski/vpn-slice#112]
Two macbooks - amd64 vs arm64.
VPN -- Cisco Anyconnect, via openconnect with vpn-slice for splitting.

amd64 -- everything is works as expected
arm64 -- connects, tun interface created, routes are installed, no any packets are sent. 

Identical commands to run openconnect/vpn-slice, same LAN/Internet connection, same user on the same VPN server.

Differences are only in MacOS versions and hardware platform:

**Software info from arm64 macos:**

% uname -a
Darwin SPG-NB-80.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

% sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

% openconnect --version
OpenConnect version v9.01
Using GnuTLS 3.7.6. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /opt/homebrew/etc/vpnc-script

% vpn-slice --version
vpn-slice 0.16.1

**Software info from amd64 macos:**

$ uname -a
Darwin asmac 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

$ sw_vers
ProductName: macOS
ProductVersion: 11.6.7
BuildVersion: 20G630

$ openconnect --version
OpenConnect version v9.01
Using GnuTLS 3.7.6. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /usr/local/etc/vpnc-script

$ vpn-slice --version
vpn-slice 0.16.1

**Comment by dlenski** [comment]
> Two macbooks - amd64 vs arm64.
> VPN -- Cisco Anyconnect, via openconnect with vpn-slice for splitting.
> 
> amd64 -- everything is works as expected
> arm64 -- connects, tun interface created, routes are installed, no any packets are sent.
> 
> Identical commands to run openconnect/vpn-slice, same LAN/Internet connection, same user on the same VPN server.

Why do you think this has anything to do with `vpn-slice`?

**Comment by sj-asm** [comment]
> Why do you think this has anything to do with `vpn-slice`?

Good question! Checked if everything is working with default scripts -- the same. Will investigate, sorry to disturbing you!
