### ISSUE TITLE
Could not install per instructions

### ISSUE THREAD

**Issue by jflorian** [dlenski/vpn-slice#12]
I do a lot of Python programming, but oddly almost never use pip because I am able to use the system packages in Fedora for most things.  When I ran into into `error: could not create '/usr/local/lib/python3.7': Permission denied` per your instructions I recalled having read about caveats of throwing sudo at pip, at least on Fedora.  A quick search led me to [this concise and helpful page](https://developer.fedoraproject.org/tech/languages/python/pypi-installation.html) where it recommended running with the `--user` option, thus:

~~~
pip3 install --user https://github.com/dlenski/vpn-slice/archive/master.zip
~~~

and this worked for me.  Perhaps worthy of a mention for Fedora users or can this be applied everywhere?  (Your `$` prompt suggests the install shouldn't need root authority.)

**Comment by mschilli87** [comment]
@dlenski: Is this still relevant? Should I put together a PR to adjust the docs or can this be closed without by now?

**Comment by dlenski** [comment]
> @dlenski: Is this still relevant? Should I put together a PR to adjust the docs or can this be closed without by now?

I'm not sure. ¯\\\_\(ツ\)\_/¯

I don't fully understand the source of the error that the OP gets when running `sudo pip3`.

**Comment by jflorian** [comment]
I don't recall what the instructions looked like back then and am too lazy to dig.  I can see however that my present setup did install as root (i.e., using `sudo` and not using `--user`) and perhaps for the very reason noted in the current instructions.
> You should install as `root` (e.g. using `sudo`), because `openconnect` or `vpnc` will need to be able to invoke `vpn-slice` while running as root
As such, I don't see this issue being relevant as I find things today.
