### ISSUE TITLE
Please release a new version of the master branch

### ISSUE THREAD

**Issue by sthysel** [dlenski/vpn-slice#128]
Currently pip and arch packages ship with version 0.16.1 that does not include the systemd-resolved fixes for Linux. These fixes added in the last 7 months seems to work fine, so a release is in order.

**Comment by ibgp2** [comment]
Same remark here.

I even implemented a `SplitDNSProvider` and once fixed, I observed that you already had an implementation in [linux.py](https://github.com/dlenski/vpn-slice/blob/master/vpn_slice/linux.py).

**linux.py**
```python
from .provider import SplitDNSProvider

class LinuxSplitDNSProvider(SplitDNSProvider):
    def configure_domain_vpn_dns(self, domains, nameservers):
        os.rename("/etc/resolv.conf", "/etc/resolv.conf.bak")
        with open("/etc/resolv.conf", "w") as f:
            for nameserver in nameservers:
                f.write("nameserver {}\n".format(nameserver))

    def deconfigure_domain_vpn_dns(self, domains, nameservers):
        os.rename("/etc/resolv.conf.bak", "/etc/resolv.conf")
```
**__main.py__**
```python
...
    if platform.startswith('linux'):
        from .linux import CheckTunDevProvider, Iproute2Provider, IptablesProvider, LinuxSplitDNSProvider, ProcfsProvider
        from .posix import DigProvider, PosixHostsFileProvider
        return dict(
            process = ProcfsProvider,
            route = Iproute2Provider,
            firewall = IptablesProvider,
            dns = DNSPythonProvider or DigProvider,
            hosts = PosixHostsFileProvider,
            domain_vpn_dns = LinuxSplitDNSProvider,
            prep = CheckTunDevProvider,
        )
...
```

**Comment by DamnedElric** [comment]
Just jumping on the band wagon. Currently getting the error "no split dns provider available; can't split dns" because the version in pip doesn't contain the recent linux changes. 

Thanks!

**Comment by ibgp2** [comment]
Hello @DamnedElric, this is precisely why I came to this thread too. You could either install `vpn-slice` through `git` instead of `pip` of fixing the two files I mentioned in my previous message, either using the files provided on git, either by fixing them as I proposed.

**Comment by sthysel** [comment]
Yes there is no issue installing the current master HEAD using `git clone...; pip install .`, its just inconvenient and confusing as you'd expect the README to align  with the latest release.

**Comment by sthysel** [comment]
Yes there is no issue installing the current master HEAD using `git clone...; pip install .`, its just inconvenient and confusing as you'd expect the README to align  with the latest release.

**Comment by dlenski** [comment]
> Currently pip and arch packages ship with version 0.16.1 that does not include the systemd-resolved fixes for Linux. These fixes added in the last 7 months seems to work fine, so a release is in order.

The split DNS support added for Linux in #118 (what you are calling "the systemd-resolved fixes for Linux") did _not_ work fine. In particular, it caused problems for users who _aren't_ using `systemd-resolved`. See https://github.com/dlenski/vpn-slice/pull/118#issuecomment-1624177196.

After I reverted #118 in a640258e8dce5bada0cf9bc8cd39edea74dc1ec1, there are no real functional differences between `v0.16.1` and current `master`: https://github.com/dlenski/vpn-slice/compare/v0.16.1..master

If/when there are new features on the `master` branch (perhaps including cleaned-up support for split DNS on Linux), I'll do a new release.
