### ISSUE TITLE
Support for attempt-reconnect reason

### ISSUE THREAD

**Issue by gmacon** [dlenski/vpn-slice#13]
OpenConnect 8.02 [added](http://www.infradead.org/openconnect/changelog.html) a new vpnc-script reason: `attempt-reconnect`. Currently, vpn-slice ignores the reconnect event, but with both before and after events, it might make more sense to do the disconnect actions before and connect actions after. Thoughts?

Hat tip to @modib for bringing this to my attention.

**Comment by dlenski** [comment]
Thanks, fixed by @doomedraven in #14.
