### ISSUE TITLE
vpn-slice==0.16.1 raise PackageNotFoundError(name)

### ISSUE THREAD

**Issue by pseregiet** [dlenski/vpn-slice#131]
EDIT: A comment on AUR says that python needs to be downgraded to 3.10.10-1 to avoid this error. So I guess vpn-slice is broken on 3.11.3 https://aur.archlinux.org/packages/vpn-slice

After system update on Arch I have this error when running vpn-slice. Mind you this is after I enter all the passwords, including 2FA from the Microsoft's app

```
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS1.2)-(ECDHE-RSA)-(AES-256-GCM).
Initiating MTU detection (min=576, max=1390)
No change in MTU after detection (was 1390)
Configured as xx.xx.xx.xx, with SSL connected and DTLS connected
Session authentication will expire at Thu May 11 11:28:33 2023

Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/vpn-slice", line 33, in <module>
    sys.exit(load_entry_point('vpn-slice==0.16.1', 'console_scripts', 'vpn-slice')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/vpn-slice", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for vpn-slice
```

**Comment by Deastrom** [comment]
ditto

**Comment by mhob** [comment]
I removed the AUR package and installed vpn-slice via pip and it worked. So this doesn't seem to be an issue with vpn-slice but with the AUR package.

**Comment by pseregiet** [comment]
> I removed the AUR package and installed vpn-slice via pip and it worked. So this doesn't seem to be an issue with vpn-slice but with the AUR package.

Thanks. I did that and it works with newest python3. I'll just add that I had to run pip install as root. When the package was installed only locally for the user vpn-slice fails to launch when used with sudo (which is how I use it with openconnect). So if you get this error:

```
Traceback (most recent call last):
  File "/home/userdir/.local/bin/vpn-slice", line 5, in <module>
    from vpn_slice.__main__ import main
ModuleNotFoundError: No module named 'vpn_slice'
```
then run 
```
pip uninstall vpn-slice
sudo pip install vpn-slice
```

**Comment by gmacon** [comment]
I'll point out that the Arch package needs to be re-built when the version of Python changes (because that changes where the files are written on disk).

Since we've concluded this is a packaging bug, I'm going to close this issue. Thanks to everyone who helped out.
