### ISSUE TITLE
Implied security risks 

### ISSUE THREAD

**Issue by cipri-tom** [dlenski/vpn-slice#2]
Hi,

Thank you for this ! Works perfectly ^^
This is more a question than an issue. I am noob with routing/networking so I was wondering if you could explain what risks, if any, I am taking by using vpn-slice. Can my network admin (who provides the VPN) identify that I have exposed the private network ?

It would be great if you could point me to some attack that could be done which would compromise the private network so that I can learn how to protect against it. 

Many thanks for making this so easy to use !

**Comment by dlenski** [comment]
It's a good question.

> Can my network admin (who provides the VPN) identify that I have exposed the private network ?

No. From the VPN administrator's perspective, there is no sign that you have configured your routing on the _client_ side differently from the default.

Perhaps they will see that you are only ever connecting to 2-3 IP addresses inside the corporate network but… so what? Maybe it's your personal practice not to use the Internet when your access is going through the corporate VPN.

>I was wondering if you could explain what risks, if any, I am taking by using vpn-slice.

By giving you more control over the routing config, vpn-slice certainly makes it _possible_ for you to do something bad or dangerous to a corporate network, which is probably why few corporate VPNs offer split tunneling by default.

* You could connect to multiple VPNs and bridge them. If you are a contractor who has access to both Apple's VPN and Samsung's VPN, and you connect to both simultaneously and configure the routing badly… they will probably not be thrilled to see packets from each others' internal networks :-p
* If you have a virus or other malware on your computer, it could steal data from the corporate network and then pass it to a server on the public internet, without the corporate firewalls having a chance to intercept its outgoing traffic.

**Comment by cipri-tom** [comment]
Awesome! Thank you very much for the explanations! And for the script too!!
