### ISSUE TITLE
vpn-slice does not tunnel IP subnets

### ISSUE THREAD

**Issue by bangn** [dlenski/vpn-slice#20]
Hi @dlenski

Firstly, thank you very much for your work on `vpn-slice`

I am trying to route the IP subnets through VPN connection using `openconnect`
and `vpn-slice`.

It works if I specify `/32` subnet. For example if I do

```
sudo openconnect \
  mywork.company \
  --protocol=gp \
  --user=username \
  --os=linux-64 \
  --usergroup=gw \
  -s \
    'vpn-slice 192.168.37.105/32 --dump --verbose'
```

I will be able to connect to `192.168.37.105` through VPN

However, if I use

```
sudo openconnect \
  mywork.company \
  --protocol=gp \
  --user=username \
  --os=linux-64 \
  --usergroup=gw \
  -s \
    'vpn-slice 192.168.37.105/31 --dump --verbose'
```

I cannot connect to `192.168.37.105`

The `--dump` and `--verbose` show this warning

```
Looking up 1 hosts using VPN DNS servers...
ESP session established with server
ESP tunnel connected; exiting HTTPS mainloop.
WARNING: Lookup for 192.168.37.105/31 on VPN DNS servers failed.
Added hostnames and aliases for 1 addresses to /etc/hosts.
Added 0 routes for named hosts.
```

Below is information of `openconnect` and `vpn-slice` I am uing

```
OpenConnect version v8.02-1
vpn-slice 0.9.1
OS Debian buster
```

Do you have any idea as why it does not work with IP subnet?

Thank you very much in advance.

Cheers
Bang

**Comment by dlenski** [comment]
`vpn-slice` uses Python's [`ipaddress` module](https://docs.python.org/3/library/ipaddress.html) to parse IP network and host addresses.

`192.168.37.105/31` _isn't_ recognized as a (canonical) IPv4 network address, nor as an IPv4 host address:

```python
>>> import ipaddress
>>> ipaddress.ip_network('192.168.37.105/31')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/ipaddress.py", line 1536, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 192.168.37.105/31 has host bits set
>>> ipaddress.ip_address('192.168.37.105/31')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '192.168.37.105/31' does not appear to be an IPv4 or IPv6 address
```

… which is why `vpn-slice` default to looking it up as a hostname.

The correct canonical address for this network would be `192.168.37.104/31`. But it turns out I can get `ipaddress` to parse it more forgivingly, simply by adding `strict=False`, so I should probably do that.

```python
>>> ipaddress.ip_network('192.168.37.105/31', strict=False)
IPv4Network('192.168.37.104/31')
```

**Comment by bangn** [comment]
Thank you very much for prompt reply.

I will try and let you know

**Comment by bangn** [comment]
Work like a charm.

Thank you very much Dan

**Comment by dlenski** [comment]
I've submitted an MR to OpenConnect to sanitize/fix these incorrectly-specified IPv4 networks before sending them to the vpnc-script:

https://gitlab.com/openconnect/openconnect/-/merge_requests/97
