### ISSUE TITLE
Need guinea pigs for -K/--prevent-idle-timeouts

### ISSUE THREAD

**Issue by dlenski** [dlenski/vpn-slice#25]
In [recent commits](https://github.com/dlenski/vpn-slice/compare/8665c2ee763f495569f982c455af73c5d20f493d..7b82124284d9b91992db85d3b7302e17e911f05c), I added a new option:

```
  -K, --prevent-idle-timeout
                        Prevent idle timeout by doing random DNS lookups
                        (interval set by $IDLE_TIMEOUT, defaulting to 10
                        minutes)
```

With this option, `vpn-slice` will keep on running in the background, and will issue randomly-timed DNS requests to a random selection of named hosts and routed IP addresses, in order to try and trick the VPN gateway to not disconnecting the client due to idle timeout. (See a4a6e778e1c4499b89494b33786dd950a8415766 for details of exactly what it does.)

I'd appreciate others testing it and letting me know if it works for you as well.

(related [OpenConnect merge-request #67](https://gitlab.com/openconnect/openconnect/merge_requests/67) from me, to export the `IDLE_TIMEOUT` variable to the script)

**Comment by soaringswine** [comment]
I'd be happy to test, but I receive the following error when I add in "--prevent-idle-timeout" with vpn-slice 0.11 on Ubuntu 18.04.3:

```
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vpn_slice/__main__.py", line 451, in main
    do_post_connect(env, args)
  File "/usr/local/lib/python3.6/dist-packages/vpn_slice/__main__.py", line 241, in do_post_connect
    if args.verbose > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by dlenski** [comment]
Thanks @soaringswine. I just fixed a dumb mistake that was causing this, in 2269a4a.

**Comment by soaringswine** [comment]
Ok, historically the VPN I connect to kicks me off after 20 or something hours even when running a ping to something on the VPN subnet.. I've just connected now and will see if I get kicked off. it's entirely possible I reach a max time exceeded or something instead of an idle timeout so this new option may not make a difference.

**Comment by dlenski** [comment]
@soaringswine, let me know if it makes any difference.

Most VPNs (certainly at least [GlobalProtect](https://gitlab.com/openconnect/openconnect/blob/master/gpst.c#L487-492), and I think AnyConnect too) differentiate between…

1. A disconnect-if-idle time: the VPN gateway will drop the connection (and invalidate the session authentication cookie) if there's no “real” traffic after that period of time. **What `vpn-slice -K` tries to do is generate some “real-looking” traffic (not entirely repetitive, but low volume) to prevent such a drop.**
2. A total session lifetime: the VPN gateway will drop the connection and invalidate the session authentication cookie after this period of time, _no matter what_. Client software can't do anything about this.
3. _(possibly)_ A key lifetime: the VPN will need to be re-keyed with new encryption keys (for ESP, TLS, DTLS, etc.) after a certain period of time. Fully-implemented client software should handle this automatically; OpenConnect does for AnyConnect, GlobalProtect, and Juniper NC at least.

If your 20-hour limit is indeed caused by the disconnect-if-idle time, and _not_ the total session lifetime, then it should do the trick. :crossed_fingers:

**Comment by soaringswine** [comment]
I definitely think I fall into category 2 as I received this: Received server disconnect: b0 'Max time exceeded'

which is definitely an improvement from getting kicked off for idle time, so it looks like the idle preventer works!!
