### ISSUE TITLE
Problems when iptables is actually nf_tables

### ISSUE THREAD

**Issue by georgegeddes** [dlenski/vpn-slice#28]
On Debian buster I was getting warnings about not blocking incoming traffic. It seems to be because the default iptables is nftables.

**Comment by dlenski** [comment]
Thanks, @georgegeddes.

I noticed you deleted the proposed patch from your report… does it not actually work as expected?

```py
class IptablesProvider(FirewallProvider):
    def __init__(self):
        self.iptables = get_executable('/sbin/iptables')
        version = subprocess.Popen([self.iptables, '--version'],
                                   stdout=subprocess.PIPE).stdout.read()
        if b'nf_tables' in version:
            self.iptables = get_executable(self.iptables + '-translate')
```

**Comment by georgegeddes** [comment]
Yeah, I noticed right after posting that that it wasn't actually working right. For now I used update-alternative to witch to iptables-legacy.

**Comment by dlenski** [comment]
Any updates on how to detect/resolve this condition?
