### ISSUE TITLE
Openconnect, is it possible to force using IPv4?

### ISSUE THREAD

**Issue by morganchenjp** [dlenski/vpn-slice#38]
Just started trying to use vpn-slice today, 
and I am using OpenConnect version v7.08-3ubuntu0.18.04.1
Cmd line as below :
` -s 'vpn-slice --verbose 10.191.0.0/16' `
But always got below error. 
Is it possibel to force it to use IPv4 ?

```
WARNING: IPv6 address or netmask set, but this version of vpn-slice has only rudimentary support for them.
WARNING: IPv6 address or netmask set, but this version of vpn-slice has only rudimentary support for them.
Blocked incoming traffic from VPN interface with iptables.
RTNETLINK answers: No buffer space available
Traceback (most recent call last):
  File "/usr/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.13', 'console_scripts', 'vpn-slice')()
  File "/export/morgan/.local/lib/python3.6/site-packages/vpn_slice/__main__.py", line 462, in main
    do_connect(env, args)
  File "/export/morgan/.local/lib/python3.6/site-packages/vpn_slice/__main__.py", line 163, in do_connect
    providers.route.add_address(env.tundev, env.myaddr6)
  File "/export/morgan/.local/lib/python3.6/site-packages/vpn_slice/linux.py", line 72, in add_address
    self._iproute('address', 'add', address, dev=device)
  File "/export/morgan/.local/lib/python3.6/site-packages/vpn_slice/linux.py", line 48, in _iproute
    subprocess.check_call(cl)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/sbin/ip', 'address', 'add', '2606:b400:c24:81:8000::27d', 'dev', 'tun0']' returned non-zero exit status 2.
Script 'vpn-slice --verbose 10.191.0.0/16' returned error 1
```

**Comment by dlenski** [comment]
`vpn-slice` itself doesn't have an option to entirely ignore IPv6 settings, but perhaps it'd be a good idea for me to add one. 

In any case, you can specify `--disable-ipv6` as an argument **to `openconnect`**, and then `vpn-slice` shouldn't receive any IPv6-related settings from the server.

> subprocess.CalledProcessError: Command '['/sbin/ip', 'address', 'add', '2606:b400:c24:81:8000::27d', 'dev', 'tun0']' returned non-zero exit status 2.

The command line that's failing to execute is `[/sbin/ip', 'address', 'add', '2606:b400:c24:81:8000::27d', 'dev', 'tun0']`. This is a very innocuous command. Are you running an ollllld kernel, <3.6.? Does [changing the IPv6 routing buffer size](https://serverfault.com/questions/614453/no-buffer-space-available-on-connect) make a difference?

**Comment by morganchenjp** [comment]
I am using Linuxmint 19.3 which derived from Ubuntu, 
Kernel is 4.15.0-88-generic #88-Ubuntu
will try disabl-ipv6 firstly. 
thanks.
