### ISSUE TITLE
possibility to provide whole domain for VPN tunelling

### ISSUE THREAD

**Issue by ciapecki** [dlenski/vpn-slice#4]
is there any possibility to provide whole domain instead of single links in domain for vpn tunneling?
e.g. 
instead of providing single subdomains
sub1.mycompany.com
sub2.mycompany.com

to be able to provide mycompany.com as attribute?

**Comment by dlenski** [comment]
I'm not really sure what you mean here.

The whole point of vpn-slice is **not** to accept the default routing and DNS servers offered by the VPN.

You can add _routing_ for a whole subnet by specifying it on the command line (e.g. `192.168.0.1/24`) but there is no way to add hostname entries for all the internal hosts that the internal DNS servers knows about.

**Comment by dlenski** [comment]
It might be possible to configure [dnsmasq](https://en.wikipedia.org/wiki/Dnsmasq) to forward requests for `*.mycompany.com` to the VPN-internal DNS servers, and to send all other DNS requests to your "normal" DNS server…

… but that's outside the scope of vpn-slice.

**Comment by ciapecki** [comment]
in mycompany.com we have a lot of internal networks that are available only via VPN
these are on the same domain mycompany.com
but in different networks:
10.165.248.252
10.236.142.18
152.68.167.141

I will have a look at dnsmasq ... thanks for the pointer

btw. 192.168.0.1/24 -> how does it work?
I tried to add 152.68.167.0/24 => but that did not produce any additional entries in /etc/hosts

**Comment by dlenski** [comment]
> btw. 192.168.0.1/24 -> how does it work?
> I tried to add 152.68.167.0/24 => but that did not produce any additional entries in /etc/hosts

That tells `vpn-slice` to add an IPv4 _route_ through the VPN tunnel interface. (That means telling Linux that you want traffic for those IP addresses to go through the VPN.) Adding a route to an IP address or a subnet **not** add hostname entries.

When you specify a host _name_ on the command line, `vpn-slice` does 2 things: (1) it uses the VPN DNS server to look up the IP address for that host and (2) it adds a route through the VPN tunnel to that specific address.

There's no way to ask a DNS server for a list of all the hosts that are part of an internal network. So there is no way to look up and add all of these hosts. ¯\\\_(ツ)\_/¯

**Comment by ClaudioLazaro** [comment]
Ola pessoal, segue a forma que eu consegui fazer funcionar no ubuntu-20.04:
Eu tentei usando o systemd-resolve, porem funcionava porem toda vez que eu passava mais de um dns server e domain funcionava o primeiro da lista os demais eram ignorados.

quando eu consultada usando o comando resolvectl nao estavam setados os demais dns server e  domain names.

Solução: 
Supondo que voce ja tenha conseguido conectar na sua vpn usando o vnp-slice, voce tem que usar o comando resolvectl para adicionar o dns e domain de forma separada.

exeplo:

sudo resolvectl -i tun0 dns tun0 10.104.211.200 10.104.91.200
sudo resolvectl -i tun0 domain tun0 mydomain01.com.br mydomain01.com.br esmydomain01.com.br uhgbrasil.com.br

esta printo pode testar.

**Comment by dlenski** [comment]
@ClaudioLazaro, I speak English, French, Spanish, and Hebrew, but not Portuguese. Please post in English.

**Comment by ClaudioLazaro** [comment]
> @ClaudioLazaro, I speak English, French, Spanish, and Hebrew, but not Portuguese. Please post in English.
I posted in english too, tank`s for touch me.
