### ISSUE TITLE
Using without sudo

### ISSUE THREAD

**Issue by Mixka** [dlenski/vpn-slice#43]
After `sudo setcap cap_net_admin+ep /usr/bin/openconnect` I can run openconnect without sudo.

Is there a way to use vpn-slice without sudo?

This is error in Centos 8 with Python 3.6:

```
  File "/home/knude/.virtualenvs/vpn-slice/bin/vpn-slice", line 8, in <module>
    sys.exit(main())
  File "/home/knude/.virtualenvs/vpn-slice/lib/python3.6/site-packages/vpn_slice/__main__.py", line 422, in main
    finalize_args_and_env(args, env)
  File "/home/knude/.virtualenvs/vpn-slice/lib/python3.6/site-packages/vpn_slice/__main__.py", line 379, in finalize_args_and_env
    if os.path.basename(exe) in ('dash','bash','sh','tcsh','csh','ksh','zsh'):
  File "/usr/lib64/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by dlenski** [comment]
> Is there a way to use vpn-slice without sudo?

Not without a workaround like `setcap`. You wouldn't want an unprivileged user to be able to manipulate network routes… would you?

> This is error in Centos 8 with Python 3.6:

As of [v0.13](https://github.com/dlenski/vpn-slice/commits/v0.13), just running `vpn-slice --help`  should work fine without root.

> ```
>     if os.path.basename(exe) in ('dash','bash','sh','tcsh','csh','ksh','zsh'):
> ```

What's happening here is that vpn-slice doesn't have permission to lookup the executable of its grandparent process.

**Comment by dlenski** [comment]
^ a0b8c2d should get you past this trivial point of failure, but you'll need to do some in-depth debugging here to figure out additional root capabilities required to run `ip route`, `iptables`, etc depending on your platform.

**Comment by Mixka** [comment]
> would you?
ofc :)
