### ISSUE TITLE
Unable to establish connection

### ISSUE THREAD

**Issue by Mayo1122** [dlenski/vpn-slice#47]
Unable to make a connection, without using vpn-slice it's working.
I'm using this command 
```
sudo openconnect https://125.209.98.228 --no-dtls -s 'vpn-slice my.mycompany.com'
```

These are messages of the terminal.

Connected as 192.168.21.2, using SSL
/bin/sh: vpn-slice: command not found
Script 'vpn-slice my.mycompany.com' returned error 127
/bin/sh: vpn-slice: command not found
Script 'vpn-slice my.mycompany.com' returned error 127

**Comment by dlenski** [comment]
>  sudo openconnect https://125.209.98.228 --no-dtls -s 'vpn-slice my.mycompany.com'

Presumably `vpn-slice` is not in the path of the root user (who is calling it). You can either install `vpn-slice` system-wide so that it is, or do something like this:

```
# Lookup full path of vpn-slice as current user, before connecting as root
# Also, you'll certainly want -v (and maybe --dump) the first time you run it.
sudo openconnect https://125.209.98.228 --no-dtls -s "$(which vpn-slice) -v" my.mycompany.com'
```

**Comment by Mayo1122** [comment]
I have used this cmd for the installation
sudo pip3 install https://github.com/dlenski/vpn-slice/archive/master.zip

Own check: sudo vpn-slice --self-test
Result: sudo: vpn-slice: command not found

Own check: vpn-slice --self-test
usage: vpn-slice [-h] [-k KILL] [-K] [--banner] [-i] [-n NAME] [-d DOMAIN]
                 [-I] [-S] [--no-host-names] [--no-short-names]
                 [--no-ns-hosts] [--nbns] [-v] [-V] [-D] [--no-fork]
                 [--ppid PPID]
                 [routes [routes ...]]
vpn-slice: error: unrecognized arguments: --self-test

cmd: which vpn-slice
Result: /usr/local/bin/vpn-slice

Cmd: sudo openconnect https://125.209.98.228 --no-dtls -s '"$(which vpn-slice) -v" my.mycompany.com'
Result:
POST https://125.209.98.228/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as 192.168.21.2, using SSL
which: no vpn-slice in (/sbin:/bin:/usr/sbin:/usr/bin)
/bin/sh:  -v: command not found
Script '"$(which vpn-slice) -v" my.mycompany.com' returned error 127
which: no vpn-slice in (/sbin:/bin:/usr/sbin:/usr/bin)
/bin/sh:  -v: command not found
Script '"$(which vpn-slice) -v" my.mycompany.com' returned error 127

cmd: sudo openconnect https://125.209.98.228 --no-dtls -s '/usr/local/bin/vpn-slice my.mycompany.com'
Result:
POST https://125.209.98.228/
XML POST enabled
Please enter your username and password.
Username:smart
Password:
POST https://125.209.98.228/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as 192.168.21.2, using SSL
WARNING: Lookup for my.mycompany.com on VPN DNS servers failed:
        The DNS operation timed out after 30.000993013381958 seconds

one more question what is "my.mycompany.com"?
Thanks

**Comment by Mayo1122** [comment]
Two more cmd for your information,
cmd: sudo which vpn-slice 
Result: which: no vpn-slice in (/sbin:/bin:/usr/sbin:/usr/bin)

cmd: which vpn-slice
/usr/local/bin/vpn-slice

**Comment by dlenski** [comment]
>  Result: sudo: vpn-slice: command not found
> 
> cmd: sudo openconnect https://125.209.98.228 --no-dtls -s '/usr/local/bin/vpn-slice my.mycompany.com'

Yes, I already responded to this.

As I wrote above: "**Presumably vpn-slice is not in the path of the root user (who is calling it). You can either install vpn-slice system-wide so that it is,** or do something like this: `sudo $(which vpn-slice)`"

You have not installed vpn-slice in a location where root can access it.

> one more question what is "my.mycompany.com"?

There was a small typo in my example there… I meant to put that in as an example of a host to lookup and add to `/etc/hosts`, but having openconnect invoke as `vpn-slice -v my.mycompany.com`.
