### ISSUE TITLE
Is there support for glob hosts?

### ISSUE THREAD

**Issue by antoyo** [dlenski/vpn-slice#57]
Hi.
I want to use this script, but there's many hosts with a predictable format that I want to use this script with, without having to list them all.
Is there a way to specify hosts with a glob, something like: `test-*.bigcorp.com`?
Thanks.

**Comment by dlenski** [comment]
>  Is there a way to specify hosts with a glob, something like: `test-*.bigcorp.com`?

Not exactly, because DNS itself doesn't support any kind of wildcard search that would allow this.

_However_, you can use most Unix shells' brace expansion mechanism `test-{foo,bar,baz,quux}.bigcorp.com` to expand and lookup a finite explicit list of hosts.

**Comment by antoyo** [comment]
I guess that's good enough for my use case.
Thanks.
