### ISSUE TITLE
Inverting the split tunnel specification?

### ISSUE THREAD

**Issue by wrosecrans** [dlenski/vpn-slice#59]
Basically, I am trying to figure out how to route everything but a certain subnet through the openconnect VPN connection.

All of the documentation for vpn-slice seems to assume I want to route only a specific subnet or handful of things through the VPN, but is it possible to do it the other way around?  Am I missing something obvious?  The VPN I am connecting to is a fairly complicated an undocumented little universe of legacy networks, I just need to keep access to a few local things.  Like `vpn-slice --everything-but importanthost1.local importanthost2.local`

Am I just missing something obvious?

**Comment by dlenski** [comment]
See #16. It should be technically fairly easy to implement, but getting the UX/error reporting for includes-vs-excludes may be a bit tricky.

Want to take a crack at a PR?
