### ISSUE TITLE
Document that openconnect script limits to a certain amount of argument, removing hosts from them

### ISSUE THREAD

**Issue by antoyo** [dlenski/vpn-slice#60]
Hi.
There seems to be a limit to the number of arguments accepted by the script sent to openconnect: some hosts were not taken into account in my case because of that.
Could you please document this behavior, suggesting to put those hosts in an external script file instead of in the `--script` argument?
Thanks.

**Comment by dlenski** [comment]
>  There seems to be a limit to the number of arguments accepted by the script sent to openconnect: some hosts were not taken into account in my case because of that.

?

There is no limit imposed by `vpn-slice` or `openconnect` itself.

What operating system are you using?

This seems like a good motivation for an implementation of #42 (support reading command-line arguments from config files).

**Comment by antoyo** [comment]
Hi.
I'm using ArchLinux.
Yes, I'm using this `openconnect --script "/path/to/vpn-slice host1 host2 ... hostN"`.

**Comment by dlenski** [comment]
@antoyo, how many of the _N_ hosts does it actually look up? Is the number consistent and repeatable? Does it depend on the _length_ of the individual hosts’ names in any way?

**Comment by antoyo** [comment]
I'll check that tomorrow.
What I remember is that I added a host at the end and was never looked up.

**Comment by dlenski** [comment]
Please do. We need some more details to understand what's going wrong here.

**Comment by antoyo** [comment]
I can't seem to reproduce the issue.
I'll reopen when I can.
