### ISSUE TITLE
KeyError: 'gateway' on MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by kim0** [dlenski/vpn-slice#66]
I mainly want to use vpn-slice to stop openconnect from overwriting my DNS configurations, but I still want access to all pushed subnets. I start vpn-slice with option `-S` only (hope this is correct). Unfortunately, I'm unable to see it working, bec it immediately errors our with the KeyError above. A `--dump` listing is below. Hope that's helpful

```
Called by /usr/local/Cellar/openconnect/8.10/bin/openconnect (PID 45008) with environment variables for vpnc-script:
  reason                  => reason=<reasons.connect: 2>
  VPNGATEWAY              => gateway=IPv4Address('168.87.2.217')
  TUNDEV                  => tundev='utun3'
  CISCO_DEF_DOMAIN        => domain=['mycompany.org']
  INTERNAL_IP4_ADDRESS    => myaddr=IPv4Address('172.28.160.43')
  INTERNAL_IP4_MTU        => mtu=1406
  INTERNAL_IP4_NETMASK    => netmask=IPv4Address('255.255.255.128')
  INTERNAL_IP4_NETMASKLEN => netmasklen=25
  INTERNAL_IP4_NETADDR    => network=IPv4Network('172.28.160.0/25')
  INTERNAL_IP4_DNS        => dns=[IPv4Address('172.26.247.19'), IPv4Address('172.25.232.19')]
  CISCO_SPLIT_INC         => nsplitinc=28
  CISCO_SPLIT_EXC         => nsplitexc=1
  IDLE_TIMEOUT            => idle_timeout=1800
  CISCO_*SPLIT_INC_*      => splitinc=[IPv4Network('173.240.76.142/32'), IPv4Network('173.240.68.18/32'), IPv4Network('173.240.75.9/32'), IPv4Network('150.175.57.150/32'), IPv4Network('150.175.58.110/32'), IPv4Network('150.175.57.50/32'), IPv4Network('150.175.58.10/32'), IPv4Network('15.131.135.0/25'), IPv4Network('15.131.130.0/23'), IPv4Network('89.202.125.44/32'), IPv4Network('89.202.125.15/32'), IPv4Network('89.202.116.103/32'), IPv4Network('89.202.116.78/32'), IPv4Network('89.202.116.69/32'), IPv4Network('89.202.116.68/32'), IPv4Network('89.202.116.62/32'), IPv4Network('15.189.160.0/24'), IPv4Network('99.247.64.0/24'), IPv4Network('99.247.32.0/29'), IPv4Network('99.247.27.0/24'), IPv4Network('192.168.0.0/16'), IPv4Network('10.0.0.0/8'), IPv4Network('15.189.128.0/19'), IPv4Network('15.141.224.0/19'), IPv4Network('15.141.0.0/19'), IPv4Network('172.16.0.0/12'), IPv4Network('168.246.0.0/16'), IPv4Network('147.167.0.0/16')]
  CISCO_*SPLIT_EXC_*      => splitexc=[IPv4Network('0.0.0.0/32')]
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.14.2', 'console_scripts', 'vpn-slice')()
  File "/usr/local/Cellar/vpn-slice/0.14.2/libexec/lib/python3.8/site-packages/vpn_slice/__main__.py", line 520, in main
    do_connect(env, args)
  File "/usr/local/Cellar/vpn-slice/0.14.2/libexec/lib/python3.8/site-packages/vpn_slice/__main__.py", line 133, in do_connect
    gwr = providers.route.get_route(env.gateway)
  File "/usr/local/Cellar/vpn-slice/0.14.2/libexec/lib/python3.8/site-packages/vpn_slice/mac.py", line 74, in get_route
    'via': info_d['gateway'],
KeyError: 'gateway'
Script 'vpn-slice -v --dump -S' returned error 1
^CSend BYE packet: Aborted by caller
```

**Comment by dlenski** [comment]
> ```py
>   File "/usr/local/Cellar/vpn-slice/0.14.2/libexec/lib/python3.8/site-packages/vpn_slice/mac.py", line 74, in get_route
>     'via': info_d['gateway'],
> KeyError: 'gateway'
> ```

I don't use macOS myself, but I'm guessing that this is happening because the route to your VPN server doesn't involve a gateway at all. Can you simply run `route -n` and check whether your default route (via WiFi or Ethernet) lacks a gateway?

Also try the latest commit, 0b6d49c, which I think should fix this.

**Comment by kim0** [comment]
That change did fix the crash, thanks!
I assume `vpn-slice -S` by default will not mess with my DNS setup (no scutil, no changing /etc/resolv.conf) .. If that's true, then I got what I came for. Thanks agina

**Comment by dlenski** [comment]
> That change did fix the crash, thanks!

Great! Does it also result in a working route to the VPN gateway, though? :sweat_smile: 

>  I assume vpn-slice -S by default will not mess with my DNS setup (no scutil, no changing /etc/resolv.conf) .. If that's true, then I got what I came for. Thanks agina

Correct. Actually, `vpn-slice` will not mess with your system DNS setup at all, ever… though we have some outstanding enhancement requests to let it do so in some limited circumstances.

**Comment by kim0** [comment]
Yes I was able to ssh into a VM behind the VPN, thanks!
