### ISSUE TITLE
Route only ssh through vpn

### ISSUE THREAD

**Issue by crichardson332** [dlenski/vpn-slice#77]
Hello, I'm wondering how to use vpn-slice to route ONLY ssh traffic through the VPN. I have to remote login to a machine that's on a secured internal network, and I have to be on the company VPN to ssh into that machine. But the VPN blocks all internet traffic, so I can't use the internet when I'm on the VPN. I want to route only ssh traffic through the VPN, and have everything else go over my normal wifi connection at home. I only need terminal access to the remote machine so ssh is sufficient. 

Can vpn-slice be used to do this? I'm on macOS btw.

**Comment by dlenski** [comment]
What do you mean by "route ONLY ssh traffic"? Do you mean inspect the packets down to the application layer, and only send through the VPN that traffic which exactly matches the `ssh` application-layer protocol ?

If so, **no**. `vpn-slice` does not do any deep packet inspection; it operates only at the IP layer.

But if what you really want is… "ONLY route IP traffic to _the IP addres of the specific host(s) that I ssh to_", then **yes**. This is  exactly the use case that I wrote vpn-slice for…

```
openconnect server.company.com --options --whatever --stuff --script "vpn-slice my-ssh-host.company.com"
```

**Comment by crichardson332** [comment]
Yes! Thank you that's exactly what I needed. Sorry I was just a bit confused about what address to pass to vpn-slice, but this works perfectly.
