### ISSUE TITLE
Not working in Kubernetes anymore.

### ISSUE THREAD

**Issue by LudwigE** [dlenski/vpn-slice#83]
Hello

I have been running vpn-slice from a kubernetes pod and it has worked great until recently. 

When running vpn-slice --self-test i get the following error.

```
WARNING: Couldn't configure firewall provider: cannot execute /sbin/iptables
******************************************************************************************
*** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
******************************************************************************************
Aborting because providers for hosts are required; use --help for more information
```
Getting following error when I try to connect:
```
Aborting because providers for hosts are required; use --help for more information
Script 'vpn-slice 192.168.199.0/24 --verbose' returned error 1
```
running vpn-slice --self-test --no-host-names get the following
```
WARNING: Couldn't configure firewall provider: cannot execute /sbin/iptables
******************************************************************************************
*** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
******************************************************************************************
Aborting because providers for hosts are required; use --help for more information
```
Running an older dockerimage with maybe an older release of vpn-slice installed works fine with just the /sbin/iptable warning. Has something changed that could have caused this and any idea what I could try?

Kind regards
Ludwig

**Comment by dlenski** [comment]
> Running an older dockerimage with maybe an older release of vpn-slice installed works fine with just the /sbin/iptable warning. 

Exact _which_ version are you running now? Exactly which is the older release that continues to work?

It seems like you may be comparing apples to oranges if other aspects of the docker image differ as well.

> Has something changed that could have caused this and any idea what I could try?

Not intentionally, but see #79 (and the resulting #81 and #82 PRs) which are related to _relaxing_ the requirement for the /etc/hosts provider. What does `vpn-slice --self-test --no-host-names --no-ns-hosts` tell you, with the latest `master` (bf445f3)?

**Comment by LudwigE** [comment]
Sorry, might be unclear. My last working docker image I build was Fri May 21 2021.
Next one, built on Mon May 31 2021 does not work anymore.

I'm installing with pip 
`pip3 install https://github.com/dlenski/vpn-slice/archive/master.zip`
Pip report both as vpn-slice (0.15)

I checked the script itself on the docker images and the one that is not working seem to have the change you are referring to. The one that works for me looks like this:
```
def do_pre_init(env, args):
    global providers
    if 'prep' in providers:
        providers.prep.create_tunnel()
        providers.prep.prepare_tunnel()

def do_disconnect(env, args):
    global providers
    for pidfile in args.kill:
        try:
            pid = int(open(pidfile).read())
        except (IOError, ValueError):
            print("WARNING: could not read pid from %s" % pidfile, file=stderr)
        else:
            try: providers.process.kill(pid)
            except OSError as e:
                print("WARNING: could not kill pid %d from %s: %s" % (pid, pidfile, str(e)), file=stderr)
            else:
                if args.verbose:
                    print("Killed pid %d from %s" % (pid, pidfile), file=stderr)

    removed = providers.hosts.write_hosts({}, args.name)
    if args.verbose:
        print("Removed %d hosts from /etc/hosts" % removed, file=stderr)

```

The one that don't:
```
def do_disconnect(env, args):
    global providers
    for pidfile in args.kill:
        try:
            pid = int(open(pidfile).read())
        except (IOError, ValueError):
            print("WARNING: could not read pid from %s" % pidfile, file=stderr)
        else:
            try: providers.process.kill(pid)
            except OSError as e:
                print("WARNING: could not kill pid %d from %s: %s" % (pid, pidfile, str(e)), file=stderr)
            else:
                if args.verbose:
                    print("Killed pid %d from %s" % (pid, pidfile), file=stderr)

    if 'hosts' in providers:
        removed = providers.hosts.write_hosts({}, args.name)
        if args.verbose:
            print("Removed %d hosts from /etc/hosts" % removed, file=stderr)


```
So it seem that I get the latest code from Pip.


Running vpn-slice --self-test --no-host-names --no-ns-hosts
on the latest version returns this:
```
WARNING: Couldn't configure firewall provider: cannot execute /sbin/iptables
******************************************************************************************
*** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
******************************************************************************************
'Namespace' object has no attribute 'hosts'
```

Kind regards
Ludwig

**Comment by vrystater** [comment]
Experiencing something similar. Adding info here in case relevant.
On Ubuntu 20.04, 20.10 and 21.04 v0.15 tag of vpn-slice works perfectly and self test passes

On master all of them fail self-test

`******************************************************************************************
*** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
******************************************************************************************
Aborting because providers for hosts are required; use --help for more information
`

And running 

`sudo vpn-slice --self-test --no-host-names --no-ns-hosts`

results in 

`******************************************************************************************
*** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
******************************************************************************************
'Namespace' object has no attribute 'hosts'
`
Currently rolled back to v0.15 tag and all is well. Posting information in the event it helps.

**Comment by DimitriPapadopoulos** [comment]
> ```
> ******************************************************************************************
> *** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
> ******************************************************************************************
> Aborting because providers for hosts are required; use --help for more information
> ```

That seems to be expected, see:
https://github.com/dlenski/vpn-slice#first-steps

> ```
> ******************************************************************************************
> *** Self-test did not pass. Double-check that you are running as root (e.g. with sudo) ***
> ******************************************************************************************
> 'Namespace' object has no attribute 'hosts'
> ```

Here is what I get with master on Ubuntu 20.04:
```
$ sudo /usr/local/bin/vpn-slice --self-test --no-host-names --no-ns-hosts --verbose --dump
***************************************************************************
*** Self-test passed. Try using vpn-slice with openconnect or vpnc now. ***
***************************************************************************
$ 
```
