### ISSUE TITLE
slice fails for me with openconnect globalprotect 

### ISSUE THREAD

**Issue by vonkad** [dlenski/vpn-slice#9]
Hello,

I would be really  thankful for some help with setting up slice. I need the VPN to get access to one server behind the firewall, https://den-dev-git-01.extendthereach.com.

Is this the right call ? Without the slice, the connection works. 

> ```
> vonkad@mycompanyDell ~/openconnect (globalprotect) $ sudo ./openconnect --protocol=gp sslvpn.mycompany.com -u dvonka -s '/home/vonkad/.local/bin/vpn-slice den-dev-git-01.extendthereach.com' --dump 
> Please enter your username and password
> Password: 
> POST https://sslvpn.mycompany.com/ssl-vpn/login.esp
> Attempting to connect to server 66.35.44.241:443
> Connected to 66.35.44.241:443
> SSL negotiation with sslvpn.mycompany.com
> Connected to HTTPS on sslvpn.mycompany.com
> > POST /ssl-vpn/login.esp HTTP/1.1d
> > Host: sslvpn.mycompany.com
> > User-Agent: PAN GlobalProtect
> > X-Pad: 000000000000000000000000000000000000000000000
> > Content-Type: application/x-www-form-urlencoded
> > Content-Length: 147
> > 
> > jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=sslvpn.mycompany.com&computer=mycompanyDell&user=dvonka&passwd=SecretPassword
> Got HTTP response: HTTP/1.1 200 OK
> Server: 
> Date: Mon, 26 Feb 2018 13:43:59 GMT
> Content-Type: application/xml; charset=UTF-8
> Content-Length: 622
> Connection: keep-alive
> ETag: "28632-1e6f-5a0a2e6e"
> Pragma: no-cache
> Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> X-FRAME-OPTIONS: DENY
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> Set-Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e; secure; HttpOnly
> HTTP body length:  (622)
> < <?xml version="1.0" encoding="utf-8"?><jnlp><application-desc><argument>(null)</argument><argument>be7c669a4bd32db811cce0f03edd9703</argument><argument>18a23d6ea3e868de7affd6f17a11d23c4515eed7</argument><argument>GP-gateway-N</argument><argument>dvonka</argument><argument>auth_sequence_emergency</argument><argument>vsys1</argument><argument>extendthereach</argument><argument>(null)</argument><argument></argument><argument></argument><argument></argument><argument>tunnel</argument><argument>-1</argument><argument>4100</argument><argument></argument><argument></argument><argument></argument></application-desc></jnlp>
> GlobalProtect login returned authentication-source=auth_sequence_emergency
> POST https://sslvpn.mycompany.com/ssl-vpn/getconfig.esp
> > POST /ssl-vpn/getconfig.esp HTTP/1.1
> > Host: sslvpn.mycompany.com
> > User-Agent: PAN GlobalProtect
> > Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e
> > X-Pad: 0000000000
> > Content-Type: application/x-www-form-urlencoded
> > Content-Length: 246
> > 
> > client-type=1&protocol-version=p1&app-version=3.0.1-10&os-version=linux-64&clientos=linux-64&hmac-algo=sha1%2cmd5&enc-algo=aes-128-cbc%2caes-256-cbc&authcookie=be7c669a4bd32db811cce0f03edd9703&portal=GP-gateway-N&user=dvonka&domain=extendthereach
> Got HTTP response: HTTP/1.1 200 OK
> Server: 
> Date: Mon, 26 Feb 2018 13:43:59 GMT
> Content-Type: application/xml; charset=UTF-8
> Content-Length: 1921
> Connection: keep-alive
> ETag: "2862c-1f2-5a0a2e6e"
> Pragma: no-cache
> Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> X-FRAME-OPTIONS: DENY
> HTTP body length:  (1921)
> < 
> < 	<response status="success">
> < 		<need-tunnel>yes</need-tunnel>
> < 		<ssl-tunnel-url>/ssl-tunnel-connect.sslvpn</ssl-tunnel-url>
> < 		<portal>GP-gateway-N</portal>
> < 		<user>dvonka</user>
> < 		<lifetime>43200</lifetime>
> < 		<timeout>7200</timeout>
> < 		<disconnect-on-idle>7200</disconnect-on-idle>
> < 		<bw-c2s>1000</bw-c2s>
> < 		<bw-s2c>1000</bw-s2c>
> < 		<gw-address>66.35.44.241</gw-address>
> < 		<ip-address>192.168.60.167</ip-address>
> < 		<netmask>255.255.255.255</netmask>
> < 		<dns>
> < 			<member>10.10.20.5</member>
> < 			<member>10.10.20.6</member>
> < 		</dns> 
> < 		<wins>
> < 		</wins> 
> < 		<default-gateway>192.168.60.167</default-gateway>
> < 		<mtu>0</mtu>
> < 		<dns-suffix>
> < 			<member>extendthereach.com</member>
> < 			<member>mycompany.com</member>
> < 		</dns-suffix> 
> < 		<no-direct-access-to-local-network>no</no-direct-access-to-local-network>
> < 		<access-routes>
> < 			<member>0.0.0.0/0</member>
> < 			<member>10.10.0.0/16</member>
> < 			<member>10.50.0.0/16</member>
> < 			<member>10.51.0.0/16</member>
> < 			<member>10.52.0.0/16</member>
> < 			<member>10.53.0.0/16</member>
> < 			<member>10.54.0.0/16</member>
> < 			<member>10.56.0.0/16</member>
> < 			<member>192.168.110.0/24</member>
> < 			<member>192.168.160.0/24</member>
> < 			<member>192.168.168.0/24</member>
> < 			<member>10.10.20.5/32</member>
> < 			<member>10.10.20.6/32</member>
> < 		</access-routes> 
> < 		<ipsec>
> < 			<udp-port>4501</udp-port>
> < 			<ipsec-mode>esp-tunnel</ipsec-mode>
> < 			<enc-algo>aes-128-cbc</enc-algo>
> < 			<hmac-algo>sha1</hmac-algo>
> < 			<c2s-spi>0x3F64D21E</c2s-spi>
> < 			<s2c-spi>0xBC9EB11F</s2c-spi>
> < 			<akey-s2c>
> < 				<bits>160</bits>
> < 				<val>5696baee6fa3b005bdfad6aa0ec2494668cf9dbc</val>
> < 			</akey-s2c> 
> < 			<ekey-s2c>
> < 				<bits>128</bits>
> < 				<val>148fdbd776651a572ed91b1148bbdae3</val>
> < 			</ekey-s2c> 
> < 			<akey-c2s>
> < 				<bits>160</bits>
> < 				<val>655b6346854195fb6428fdf3ad474beecaa39e33</val>
> < 			</akey-c2s> 
> < 			<ekey-c2s>
> < 				<bits>128</bits>
> < 				<val>4274ac37fe102ae12b6c189a4fbb8326</val>
> < 			</ekey-c2s> 
> < 		</ipsec> 
> < 	</response>
> Tunnel timeout (rekey interval) is 120 minutes.
> TCP_INFO rcv mss 1460, snd mss 1460, adv mss 1460, pmtu 1500
> No MTU received. Calculated 1422
> POST https://sslvpn.mycompany.com/ssl-vpn/hipreportcheck.esp
> > POST /ssl-vpn/hipreportcheck.esp HTTP/1.1
> > Host: sslvpn.mycompany.com
> > User-Agent: PAN GlobalProtect
> > Cookie: PHPSESSID=f3f7bb2a35954f6f6c900d11983ad36e
> > X-Pad: 00000000000000000000000000000000000000000000
> > Content-Type: application/x-www-form-urlencoded
> > Content-Length: 212
> > 
> > client-role=global-protect-full&authcookie=be7c669a4bd32db811cce0f03edd9703&portal=GP-gateway-N&user=dvonka&domain=extendthereach&computer=mycompanyDell&client-ip=192.168.60.167&md5=32b43a0c73f194a07188858b8b15ccb3
> Got HTTP response: HTTP/1.1 200 OK
> Server: 
> Date: Mon, 26 Feb 2018 13:43:59 GMT
> Content-Type: application/xml; charset=UTF-8
> Content-Length: 107
> Connection: keep-alive
> ETag: "2862f-63c-5a0a2e6e"
> X-Content-Type-Options: nosniff
> Pragma: no-cache
> Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Content-Security-Policy: default-src 'self'
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> X-FRAME-OPTIONS: DENY
> HTTP body length:  (107)
> < 
> < 	<response status="success">
> < 		<hip-report-needed>yes</hip-report-needed>
> < 		<delay>0</delay>
> < 	</response>
> Gateway says HIP report submission is needed.
> WARNING: Server asked us to submit HIP report with md5sum 32b43a0c73f194a07188858b8b15ccb3.
> VPN connectivity may be disabled or limited without HIP report submission.
> You need to provide a --csd-wrapper argument with the HIP report submission script.
> Send ESP probes
> Connected as 192.168.60.167, using SSL
> Traceback (most recent call last):
>   File "/home/vonkad/.local/bin/vpn-slice", line 11, in <module>
>     load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
>   File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 294, in main
>     env = parse_env()
>   File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 244, in parse_env
>     assert net.netmask==nm
> AssertionError
> Script '/home/vonkad/.local/bin/vpn-slice den-dev-git-01.extendthereach.com' returned error 1
> Traceback (most recent call last):
>   File "/home/vonkad/.local/bin/vpn-slice", line 11, in <module>
>     load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
>   File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 294, in main
>     env = parse_env()
>   File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 244, in parse_env
>     assert net.netmask==nm
> AssertionError
> Script '/home/vonkad/.local/bin/vpn-slice den-dev-git-01.extendthereach.com' returned error 1
> ESP session established with server
> ESP tunnel connected; exiting HTTPS mainloop.
> ```

**Comment by dlenski** [comment]
vpn-slice is failing an assertion because the split-tunnel netmasks it's receiving apparently don't have the expected bit pattern: `assert net.netmask==nm`

Try adding an additional `-D`/`--dump` parameter **for `vpn-slice` itself**, as follows:

```
sudo ./openconnect --protocol=gp sslvpn.mycompany.com -u dvonka -s '/home/vonkad/.local/bin/vpn-slice --dump den-dev-git-01.extendthereach.com' --dump 
```

… this should cause it to print out all the variables that it's passed. What does it show you? Does one of the `CISCO_SPLIT_INC_x_MASK` not match the `CISCO_SPLIT_INC_x_MASKLEN`?

**Comment by vonkad** [comment]
I'm not getting any such list when calling 
``
sudo ./openconnect --protocol=gp sslvpn.mycompany.com -u dvonka -s '/home/vonkad/.local/bin/vpn-slice --dump den-dev-git-01.extendthereach.com'

**Comment by vonkad** [comment]
vpn-slice 0.2
OpenConnect version v7.08-265-gae48121
Using GnuTLS. Features present: PKCS#11, HOTP software token, TOTP software token, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp

**Comment by vonkad** [comment]
I manager to add a print into the python code
VPN connectivity may be disabled or limited without HIP report submission.
You need to provide a --csd-wrapper argument with the HIP report submission script.
Connected as 192.168.60.179, using SSL
net.netmask=255.255.255.255, nm=255.255.255.255
net.netmask=255.255.255.255, nm=255.255.255.255
net.netmask=255.255.255.0, nm=255.255.255.0
net.netmask=255.255.255.0, nm=255.255.255.0
net.netmask=255.255.255.0, nm=255.255.255.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=0.0.0.0, nm=255.255.255.255
Traceback (most recent call last):
  File "/home/vonkad/.local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
  File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 295, in main
    env = parse_env()
  File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 245, in parse_env
    assert net.netmask==nm
AssertionError
Script '/home/vonkad/.local/bin/vpn-slice -D extendthereach.com' returned error 1
net.netmask=255.255.255.255, nm=255.255.255.255
net.netmask=255.255.255.255, nm=255.255.255.255
net.netmask=255.255.255.0, nm=255.255.255.0
net.netmask=255.255.255.0, nm=255.255.255.0
net.netmask=255.255.255.0, nm=255.255.255.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=255.255.0.0, nm=255.255.0.0
net.netmask=0.0.0.0, nm=255.255.255.255
Traceback (most recent call last):
  File "/home/vonkad/.local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
  File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 295, in main
    env = parse_env()
  File "/home/vonkad/.local/lib/python3.5/site-packages/vpn_slice/main.py", line 245, in parse_env

**Comment by dlenski** [comment]
Right. I still don't understand where that last one is coming from.

Pull the commit I just pushed (cacc6289e31b80836dfbe8e66d6483e4e0d6e771) which will provide a more verbose error message about which of the splits is actually causing the failure.

**Comment by vonkad** [comment]
You need to provide a --csd-wrapper argument with the HIP report submission script.
Send ESP probes
Connected as 192.168.60.197, using SSL
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
  File "/usr/local/lib/python3.5/dist-packages/vpn_slice-0.1-py3.5.egg/vpn_slice/main.py", line 295, in main
  File "/usr/local/lib/python3.5/dist-packages/vpn_slice-0.1-py3.5.egg/vpn_slice/main.py", line 245, in parse_env
AssertionError: Netmask supplied in CISCO_SPLIT_INC_12_MASK (255.255.255.255) does not match the 0-bit prefix (_MASKLEN) of the network address 0.0.0.0 (_ADDR)
	255.255.255.255 != 0.0.0.0
Script '/usr/local/bin/vpn-slice --dump den-dev-git-01.extendthereach.com' returned error 1
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.1', 'console_scripts', 'vpn-slice')()
  File "/usr/local/lib/python3.5/dist-packages/vpn_slice-0.1-py3.5.egg/vpn_slice/main.py", line 295, in main
  File "/usr/local/lib/python3.5/dist-packages/vpn_slice-0.1-py3.5.egg/vpn_slice/main.py", line 245, in parse_env
AssertionError: Netmask supplied in CISCO_SPLIT_INC_12_MASK (255.255.255.255) does not match the 0-bit prefix (_MASKLEN) of the network address 0.0.0.0 (_ADDR)
	255.255.255.255 != 0.0.0.0
Script '/usr/local/bin/vpn-slice --dump den-dev-git-01.extendthereach.com' returned error 1
ESP session established with server

**Comment by dlenski** [comment]
Right, now it explains exactly what is going on. `vpn-slice` apparently receives the 3 following variables.

```
CISCO_SPLIT_INC_12_MASK=255.255.255.255   # ????
CISCO_SPLIT_INC_12_MASKLEN=0
CISCO_SPLIT_INC_12_ADDR=0.0.0.0
```

These are not internally consistent with each other. It's openconnect's fault.

I don't understand why openconnect is doing this, because it's a perfectly normal use case… I recall having connected to other VPNs with `0.0.0.0/0` "splits" (GP, AnyConnect, Juniper) and it had the expected behavior and worked fine with `vpn-slice`.

You might need to add some debugging/logging statements around here to figure out why the split is getting output with the wrong mask: https://github.com/dlenski/openconnect/blob/HEAD/script.c#L131-L152

**Comment by dlenski** [comment]
Are you building/running on a 32-bit or 64-bit system, by the way? I'm wondering if there's some architecture where [this](https://github.com/dlenski/openconnect/blob/HEAD/script.c#L82-L85) doesn't work.

**Comment by vonkad** [comment]
this is 64bit linux mint

**Comment by dlenski** [comment]
Thank you very much for helping me debug this. This was a bug in openconnect (introduced by me :man_facepalming: :man_facepalming: :man_facepalming:).

Please pull and build the latest version of [the `globalprotect` branch of openconnect-gp](https://github.com/dlenski/openconnect/tree/globalprotect) including a1f97f0 and it should work now.

I need to send this patch upstream too…

**Comment by vonkad** [comment]
Dan, thanks a lot ! It works fine now. I'm based in Central Europe and my company in Colorado. The VPN they give me slows Internet access to local resources down 100 times, as every request gets sent to the US and back. Being able to use the VPN just for the resources that actually require it is a great relief.  

So thank **you** for helping me with this.  If you ever come to Prague, do not forget I owe you a drink.

**Comment by dlenski** [comment]
:ok_hand:
