### ISSUE TITLE
5d68494 undone by ba76f82

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [dlenski/vpn-slice#91]
Commit ba76f82 modified commit 5d68494 from #86. Perhaps 5d68494 was wrong, but now we have the same LGTM alert again:
> Variable defined multiple times
>
> This assignment to 'g' is unnecessary as it is redefined [`here`](https://lgtm.com/projects/g/dlenski/vpn-slice/snapshot/75e9b2b1ae4b2f5368fb28c83ad0ede9fbc13992/files/vpn_slice/__main__.py#xb37237353881824d:1) before this value is used.

See:
https://lgtm.com/projects/g/dlenski/vpn-slice/snapshot/75e9b2b1ae4b2f5368fb28c83ad0ede9fbc13992/files/vpn_slice/__main__.py#x9a23f0fcaee3a0f5:1

**Comment by dlenski** [comment]
Derp :man_facepalming: … thanks.
