### ISSUE TITLE
Make location of the iptables executable configurable

### ISSUE THREAD

**Issue by allanadair** [dlenski/vpn-slice#96]
The location of the iptables executable is currently hardcoded to "/sbin/iptables". It would be nice to have this location configurable.

**Comment by dlenski** [comment]
Is there a Linux distribution that installs it in a different path?

**Comment by allanadair** [comment]
Yes, GuixSD and likely also NixOS.

**Comment by allanadair** [comment]
@dlenski, is this something that you'd be okay with? I'd be happy to make a change and issue a pull request. Please let me know if my efforts might not be wasted and if you have any opinions on how this should be implemented.

**Comment by dlenski** [comment]
I'd like a solution that minimizes the requirement for users to configure something that vpn-slice should be able to figure out on its own.

How about something like this? Will this Just Work on GuixSD/NixOS and _also_ on Linux distributions that use the standard `/sbin/ip`?

```diff
diff --git a/vpn_slice/util.py b/vpn_slice/util.py
index 7100d61..bad48f9 100644
--- a/vpn_slice/util.py
+++ b/vpn_slice/util.py
@@ -3,12 +3,18 @@ import os.path
 from shutil import which
 
 
-def get_executable(path):
-    path = which(os.path.basename(path)) or path
-    if not os.access(path, os.X_OK):
-        raise OSError('cannot execute {}'.format(path))
-    return path
+def get_executable(*paths, fallback_to_which=True):
+    bn = os.path.basename(paths[0])
+    for path in paths:
+        if os.access(path, os.X_OK):
+            return path
+    if fallback_to_which:
+        path = which(bn)
+        if path and os.access(path, os.X_OK):
+            return path
+    raise OSError('cannot find {} (tried {}{})'.format(
+        bn, ', '.join(paths), ('$PATH' if fallback_to_which else '')))
         
 
 class slurpy(dict):
     """Quacks like a dict and an object"""
diff --git a/vpn_slice/linux.py b/vpn_slice/linux.py
index 2082a38..f0623e2 100644
--- a/vpn_slice/linux.py
+++ b/vpn_slice/linux.py
@@ -25,7 +25,7 @@ class ProcfsProvider(PosixProcessProvider):
 
 class Iproute2Provider(RouteProvider):
     def __init__(self):
-        self.iproute = get_executable('/sbin/ip')
+        self.iproute = get_executable('/sbin/ip', '/whatever/path/GuixSD/uses/ip', '/NixOS/bin/ip')
 
     def _iproute(self, *args, **kwargs):
         cl = [self.iproute]
```

**Comment by allanadair** [comment]
@dlenski, sorry for the late response, and I think that the "which" functionality works great. I had a careless misunderstanding of how get_executable worked and I apologize for being hasty and not putting forth due diligence!

Having said that, I did have some initial errors regarding the script finding iptables, but it may not have been in $PATH at the time. I don't think that any actions needs to be taken and thank you for your wonderful work on vpn-slice. I can confirm that it's working great for me on GuixSD as is.
